// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcrMUyyZyWubQVphSIZFl0tF3aSMOoUE',
    appId: '1:195820233000:web:972b7388323cb7991e701d',
    messagingSenderId: '195820233000',
    projectId: 'connectme-app-b0fba',
    authDomain: 'connectme-app-b0fba.firebaseapp.com',
    storageBucket: 'connectme-app-b0fba.firebasestorage.app',
    measurementId: 'G-35BKWWP257',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCftThKNzTloXX4s2w4OpCig-gzPMw-cb0',
    appId: '1:195820233000:android:cf88181e675165261e701d',
    messagingSenderId: '195820233000',
    projectId: 'connectme-app-b0fba',
    storageBucket: 'connectme-app-b0fba.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVVtczas_GCu_tRO1a9Igbh_xS-JCYEg',
    appId: '1:195820233000:ios:52cce45af8a9e7d71e701d',
    messagingSenderId: '195820233000',
    projectId: 'connectme-app-b0fba',
    storageBucket: 'connectme-app-b0fba.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCVVtczas_GCu_tRO1a9Igbh_xS-JCYEg',
    appId: '1:195820233000:ios:52cce45af8a9e7d71e701d',
    messagingSenderId: '195820233000',
    projectId: 'connectme-app-b0fba',
    storageBucket: 'connectme-app-b0fba.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUcrMUyyZyWubQVphSIZFl0tF3aSMOoUE',
    appId: '1:195820233000:web:a7bf1ca0181e17e91e701d',
    messagingSenderId: '195820233000',
    projectId: 'connectme-app-b0fba',
    authDomain: 'connectme-app-b0fba.firebaseapp.com',
    storageBucket: 'connectme-app-b0fba.firebasestorage.app',
    measurementId: 'G-1G30FM1B0K',
  );
}
